"""improve interview question

Revision ID: 0fcfc6916b3c
Revises: f8c415bf15cc
Create Date: 2026-07-21 10:58:12.926667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fcfc6916b3c'
down_revision: Union[str, Sequence[str], None] = 'f8c415bf15cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('expected_skill', sa.String(length=100), nullable=True))
    op.add_column('interview_questions', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('interview_questions', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('interview_questions', sa.Column('asked', sa.Boolean(), nullable=True))
    op.alter_column('interview_questions', 'question',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interview_questions', 'topic',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_questions', 'topic',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('interview_questions', 'question',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('interview_questions', 'asked')
    op.drop_column('interview_questions', 'status')
    op.drop_column('interview_questions', 'category')
    op.drop_column('interview_questions', 'expected_skill')
    # ### end Alembic commands ###
