"""add password reset fields

Revision ID: 59dc8c99e206
Revises: d86ad0d5151d
Create Date: 2026-07-29 15:06:46.733937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59dc8c99e206'
down_revision: Union[str, Sequence[str], None] = 'd86ad0d5151d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expiry')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
