"""add recommendation and ai analysis

Revision ID: 6887b3e636b4
Revises: 8ff11a2fa0fb
Create Date: 2026-07-21 14:15:31.598523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6887b3e636b4'
down_revision: Union[str, Sequence[str], None] = '8ff11a2fa0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_answers', sa.Column('ai_strengths', sa.Text(), nullable=True))
    op.add_column('interview_answers', sa.Column('ai_weaknesses', sa.Text(), nullable=True))
    op.drop_column('interview_questions', 'asked')
    op.add_column('interviews', sa.Column('recommendation', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'recommendation')
    op.add_column('interview_questions', sa.Column('asked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('interview_answers', 'ai_weaknesses')
    op.drop_column('interview_answers', 'ai_strengths')
    # ### end Alembic commands ###
