"""update interview reports

Revision ID: 72d59468c8cb
Revises: 6d3aa2106726
Create Date: 2026-07-19 14:12:33.056777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d59468c8cb'
down_revision: Union[str, Sequence[str], None] = '6d3aa2106726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_reports', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('interview_reports', sa.Column('weaknesses', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_reports', 'weaknesses')
    op.drop_column('interview_reports', 'strengths')
    # ### end Alembic commands ###
